### ISSUE TITLE
Improve verification of all fields from configuration

### ISSUE THREAD

**Issue by snd3r** [EvotecIT/PSWinReporting#16] opened 2018-11-01 07:41 UTC
What do you think about changes in PR https://github.com/EvotecIT/PSWinReporting/pull/15 ?
I don't see the need for arrays, maybe it is worth simplifying them to one flag?

**Comment by PrzemyslawKlys** [comment] 2018-11-01 08:12
One flag would mean it would terminate on first error and not display everything. PR looks good to me.

Only thing I was thinking to do is modify Test-Key (in PSSharedGoods) and add an optional parameters -Type and Value where 'Type' would be [bool], [int], [int[]] and so on and Value would be value read from configuration. That way one could make sure the values are as expected? 

What do you think?

**Comment by PrzemyslawKlys** [comment] 2018-11-01 08:17
Or even have third parameter if the value should be somewhat limited or exactly as request. But maybe it's too hard to build dynamic function for that.

**Comment by snd3r** [comment] 2018-11-01 10:43
> One flag would mean it would terminate on first error and not display everything.

No, I do not want to break the behavior, just simplify the code.
For example:

```
    # Configuration successful check flag
    $Success = $true

    #region ReportOptions
    $Success = $Success -and (Test-Key $ReportOptions "ReportOptions" "JustTestPrerequisite" -DisplayProgress $true)
    $Success = $Success -and (Test-Key $ReportOptions "ReportOptions" "AsExcel" -DisplayProgress $true)
    $Success = $Success -and (Test-Key $ReportOptions "ReportOptions" "AsCSV" -DisplayProgress $true)
    $Success = $Success -and (Test-Key $ReportOptions "ReportOptions" "AsHTML" -DisplayProgress $true)
    $Success = $Success -and (Test-Key $ReportOptions "ReportOptions" "SendMail" -DisplayProgress $true)
    $Success = $Success -and (Test-Key $ReportOptions "ReportOptions" "OpenAsFile" -DisplayProgress $true)
    $Success = $Success -and (Test-Key $ReportOptions "ReportOptions" "KeepReports" -DisplayProgress $true)
    if (Test-Key $ReportOptions "ReportOptions" "KeepReports" -DisplayProgress $true) {
        if (-not (Test-Path $ReportOptions.KeepReportsPath -PathType Container)) {
            $Success = $false
            Write-Color @script:WriteParameters -Text "[-] ", "Path in configuration of ", "ReportOptions.KeepReportsPath", " doesn't exist." -Color White, White, Red, White
        }
    }
```

>Only thing I was thinking to do is modify Test-Key (in PSSharedGoods) and add an optional parameters -Type and Value where 'Type' would be [bool], [int], [int[]] and so on and Value would be value read from configuration. That way one could make sure the values are as expected?

I think about this when I added path checking to the configuration check function.
At the beginning, I didn’t want to add an imperative code to an almost completely declarative function, but after a few experiments, I decided that increasing abstraction and the additional complication of this function do not make the code simpler and more convenient.
In the future, the situation may change, but now I am ready to vote for a more direct way.

**Comment by PrzemyslawKlys** [comment] 2018-11-01 10:57
Are you saying its not worth to add checks to Test-Key?

**Comment by snd3r** [comment] 2018-11-01 11:15
I think if we will expand Test-Key function, then in the end we will write another Pester.

**Comment by snd3r** [comment] 2018-11-01 12:12
@PrzemyslawKlys what do you think about this way:
https://github.com/snd3r/PSWinReporting/blob/Test-Configuration/Private/Test-Configuration.ps1

**Comment by snd3r** [comment] 2018-11-01 12:34
PR https://github.com/EvotecIT/PSWinReporting/pull/18

**Comment by PrzemyslawKlys** [comment] 2018-11-01 14:46
Looks

**Comment by PrzemyslawKlys** [comment] 2018-11-01 14:47
Looks like it's not working from top to bottom:

![image](https://user-images.githubusercontent.com/15063294/47858866-41756380-dded-11e8-9013-fb662eda20dc.png)

My guess it should not terminate until it reports everything. And it seems it didn't display half of tests to me. 

I'm trying the default RunMe-Report.ps1

**Comment by PrzemyslawKlys** [comment] 2018-11-01 14:48
It also displays some things twice 

![image](https://user-images.githubusercontent.com/15063294/47859036-9fa24680-dded-11e8-9276-2f5a12c2e7bd.png)

**Comment by PrzemyslawKlys** [comment] 2018-11-01 14:50
And out of order (I guess hashtable needs to be updated to contain [ordered])

**Comment by snd3r** [comment] 2018-11-02 06:57
Fix incorrect display of validation results.
Now I think it is worth thinking about which parameters are mandatory, to reduce noise.

**Comment by snd3r** [comment] 2018-11-02 07:54
Found an unexpected side effect with log configuration if you do not have rights to write by LogFile    path.

>     DisplayConsole        = @{
>         ShowTime   = $true
>         LogFile    = 'C:\PSWinReporting.log'
>         TimeFormat = 'yyyy-MM-dd HH:mm:ss'
>     }

**Comment by PrzemyslawKlys** [comment] 2018-11-02 08:11
IF LogFile doesn't work PSWriteColor (also a repo on my org) should terminate silently. What other side effect you mean?

**Comment by PrzemyslawKlys** [comment] 2018-11-02 08:48
As for mandatory.. well SQLTableMapping is actually optional. Without it PSWinReporting will do mapping automatically. So it's not required, and can be added in multiple places.

**Comment by snd3r** [comment] 2018-11-02 10:16
> IF LogFile doesn't work PSWriteColor (also a repo on my org) should terminate silently. What other side effect you mean?

In the process of checking the configuration, the value of the global variable ($script:WriteParameters) changes
https://github.com/EvotecIT/PSWinReporting/pull/24

**Comment by PrzemyslawKlys** [comment] 2018-11-02 13:38
Well that was by design. If configuration is not set it should use the default $Script:WriteParameters (and it's set in DefaultParameters.ps1 therefore it exists and is there specifically for Testing configuration. Also not sure why you decide to "hardcode" each line with settings instead of using splash in the beginning for this? Even if we were to go with your approach one local splash would be better? But still I would like to know what is the problem with approach I took ? :)

**Comment by snd3r** [comment] 2018-11-02 16:01
> Well that was by design.

The problem I'm talking about comes up earlier.
The point of the problem is that configuration checking process changes the state of the report building script. This is the side effect.

How does it up?

Setting of default values:
```
DisplayConsole        = @{
    ShowTime   = $true
    LogFile    = 'C:\PSWinReporting.log'
    TimeFormat = 'yyyy-MM-dd HH:mm:ss'
}
```

Configuration hashtable:
```
DisplayConsole        = @{
        ShowTime   = $true
        LogFile    = 'C:\PSWinReporting.log'
        TimeFormat = 'yyyy-MM-dd HH:mm:ss'
}
```
Global variable names and variable names in the configuration hashtable are the same. At that moment when the validation function checks the values in the configuration, global variables change their state.
In practice, this looks like the start logging in the process of checking the configuration, and not the transfer of these values to the script of the report. It is rather strange to start each new log with a part of the configuration validation process entries.
This is not expected behavior.

**Comment by PrzemyslawKlys** [comment] 2018-11-02 18:43
I understand. Then in my opinion there should be simple check for existence of that in $Configuration and if it does set variables and then continue rechecking. In other words I prefer "visually" consistent configuration check and some overhead of one check (or just try to simply use configuration display console variable) then using defaults in display. My intention is to keep visual output consistent from start to end. If you use the "builtin" setup for Configuration and then user completely changed how it's supposed to look it will be visually bad.

**Comment by PrzemyslawKlys** [comment] 2018-11-08 11:46
Are you going to be closing this? Or should I take over at some point later?

**Closed** 2018-11-19 11:15 UTC
